name: Content update request
description: Request an update to training, FAQs, or instructions
title: "Content update: "
labels: ["content"]
body:
  - type: textarea
    id: issue
    attributes:
      label: What needs to change
      description: Describe the needed update and why
    validations:
      required: true
  - type: textarea
    id: source
    attributes:
      label: Approved source
      description: Provide the approved page or workbook section this should come from
    validations:
      required: true
  - type: checkboxes
    id: checks
    attributes:
      label: Safety checks
      options:
        - label: No personal data capture introduced
          required: true
        - label: No escalation promises introduced
          required: true
        - label: Tested with standard test set after update
          required: true
